opt_out_usage

# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:

default_platform :ios

platform :ios do
  before_all do
    get_changelog_from_git
    get_version_from_date
  end

  desc "Run unit tests"
  lane :shared_tests do |options|
    cocoapods(repo_update: ENV['REM_FL_CP_REPO_UPDATE'] || false)

    scan(
      clean: true,
      skip_build: true,
      result_bundle: true,
      output_directory: './artifacts/unit-tests',
      scheme: ENV['REM_FL_TESTS_SCHEME'] || 'Tests',
      device: ENV['REM_FL_TESTS_DEVICE'] || 'iPhone 11',
      code_coverage: true,
      slack_only_on_failure: true,
      skip_slack: ENV['PREVIOUS_BUILD_STATUS'] == 'error', # var defined in Bitrise step
      output_types: 'json-compilation-database,html,junit',
      output_files: 'compile_commands.json,report.html,report.junit',
      xcargs: 'COMPILER_INDEX_STORE_ENABLE=NO') # see https://github.com/oclint/oclint/issues/462

    slather(
      output_directory: './artifacts/coverage',
      scheme: ENV['REM_FL_TESTS_SCHEME'] || 'Tests',
      cobertura_xml: true,
      proj: ENV['REM_FL_TESTS_PROJECT'],
      workspace: ENV['REM_FL_TESTS_WORKSPACE'],
      binary_basename: ENV['REM_FL_TESTS_SLATHER_BASENAME'],
      ignore: '../*')

    lint_module
    format_objc(check_only: true)
  end

  desc "Build a sample"
  lane :shared_sample do |options|

    # Increment version
    increment_build_number(build_number: lane_context[SharedValues::R_VERSION_FROM_DATE], xcodeproj: ENV['REM_FL_SAMPLE_PROJECT'])
    increment_version_number(version_number: lane_context[SharedValues::R_VERSION_FROM_DATE], xcodeproj: ENV['REM_FL_SAMPLE_PROJECT'])

    # Install pods
    cocoapods(podfile: ENV['REM_FL_SAMPLE_PODFILE'] || 'Samples/Podfile', repo_update: ENV['REM_FL_CP_REPO_UPDATE'] || false)

    # Build sample
    gym(
      configuration: "Release",
      output_directory: './artifacts/device',
      workspace: ENV['REM_FL_SAMPLE_WORKSPACE'],
      codesigning_identity: 'iPhone Distribution',
      export_method: 'enterprise',
      export_team_id: ENV['REM_FL_EXPORT_TEAM_ID'],
      export_options: {
        uploadBitcode: false,
        compileBitcode: false,
      },
      scheme: ENV['REM_FL_SAMPLE_SCHEME'])
  end

  desc "Build everything"
  lane :shared_ci do |options|
    ENV['FL_COCOAPODS_VERBOSE'] = "1"
    shared_tests(options)
    shared_sample(options)
  end

  desc 'Module Pre-Release checks'
  lane :release do |options|

    release_tag = version_get_podspec(path: ENV['REM_FL_PODSPEC_FILE'])
    module_name = options[:module]
    release_branch = options[:branch]

    # Remove the newline character from the release_tag otherwise it won't enter into if statement
    release_tag = release_tag.to_s.strip

    unless release_tag.empty?
      if !git_tag_exists(tag: "#{release_tag}")
        puts "#{release_tag} version doesn't exist, it will be tagged to master branch and push it to the remote. After the version is tagged, run 'release' lane again"

      ensure_git_branch(
          branch: "#{release_branch}"
      )

      add_git_tag(
         tag: "#{release_tag}"
      )
      sh "git push origin #{release_tag}"

      end
    end

    sh 'launchctl remove com.apple.CoreSimulator.CoreSimulatorService || true'
    stg_lint

    puts "generate documenation for #{module_name} version #{release_tag}"
    documentation(
      module_name: module_name,
      module_version: release_tag
    )
  end

  private_lane :lint_podspec do |options|
    pod_lib_lint(sources: [options[:source], "https://github.com/CocoaPods/Specs"], allow_warnings: true, verbose: false)
  end

  desc 'Lint the podspec on STG spec repo'
  lane :stg_lint do
    lint_podspec(source: ENV['REM_FL_STG_SPEC_REPO'])
  end

  desc 'Lint the podspec on PROD spec repo'
  lane :prd_lint do
    lint_podspec(source: ENV['REM_FL_SPEC_REPO'])
  end

  lane :lint_module do
  	check_artifacts_dir

    if is_ci?
      type = 'pmd'
      ocpath = './artifacts/lint-results.xml'
    else
      type = 'html'
      ocpath = './artifacts/lint-results.html'
    end

    module_name = ENV['REM_MODULE_NAME'] || ENV['REM_FL_TESTS_SLATHER_BASENAME']

    begin
      oclint(
        compile_commands: './artifacts/unit-tests/compile_commands.json',
        select_regex: module_name + '/',
        report_type: type,
        report_path: ocpath,
        max_priority_1: 10,
        max_priority_2: 50,
        max_priority_3: 100,
        disable_rules: ['LongLine'])
    rescue
      UI.error '`oclint` found a problem. Please check ' + ocpath
    end

    if File.exist?('../.swiftlint.yml')
      begin
        swiftlint(
          mode: :lint,
          strict: true,
          config_file: '.swiftlint.yml',
          ignore_exit_status: false)
      rescue
        UI.error '`swiftlint` found a problem. Please check the logs above'
        raise
      end
    else
      UI.important 'No `.swiftlint.yml` file found. Skipping SwiftLint step'
    end
    
  end

  desc "Generate documentation for module"
  lane :generate_docs do |options|
    documentation(
      module_name: options[:module_name],
      module_version: options[:module_version]
    )
  end

  desc "Generate Jazzy documentation for module and deploy to GitHub Pages"
  lane :deploy_ghpages do |options|
    check_artifacts_dir
    gh_pages(
      ghpages_url: options[:ghpages_url],
      github_token: options[:github_token]
    )
  end

  desc "Set up project, including git hooks"
  lane :setup_project do
    setup_git_hooks
  end

  desc "Format Objective-C code using clang-format tool"
  lane :format_objc do |options|
    apply_codestyle(options)
  end

  def check_artifacts_dir
    Dir.mkdir '../artifacts' unless File.directory?('../artifacts')
  end
end
# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
