#!/bin/sh

export PATH=/usr/local/bin:$PATH

# run clang-format on all .m and .h files
find . -iname *.h -o -iname *.m | xargs clang-format -style=file -output-replacements-xml |
  grep "<replacement " >/dev/null

# if "<replacement " is found it means that clang-format wants to make changes
if [ $? -ne 1 ]; then
    echo "\n\nFiles do not match clang-format.\nRun 'fastlane ios format_objc' to re-format or commit with --no-verify."
    exit 1
fi
